language: python

os:
  - linux

dist: xenial

python:
  - "3.7"

before_install:
  - pip install ablog

script:
  - ablog build

after_success:
  - git config --global user.name "m-yama"
  - git config --global user.email "myama.1122@outlook.jp"
  - git config --global push.default simple
  - ablog deploy --push-quietly --github-token=DEPLOY_KEY -m="`git log -1 --pretty=%B`" --github-ssh=False
